name: Deploy

on:
  push:
    branches:
      - main
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Service
        run: pnpm build:service

      - name: Install wrangler
        run: npm install -g wrangler

      - name: Verify Cloudflare API Token
        run: |
          echo "Verifying Cloudflare API Token..."
          wrangler whoami

      - name: Apply D1 Migrations
        run: |
          cd dist/service
          wrangler d1 migrations apply web-archive --remote
          rm -rf ./src/sql

      - name: Deploy
        run: cd dist/service && wrangler pages deploy

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
